### ISSUE TITLE
Multi-Trait Manhattan Plot Issues

### ISSUE THREAD

**Issue by jhurst5** [XiaoleiLiuBio/rMVP#25]
Hello,

I am currently using MVP.Report() to make a multi trait Manhattan plot. There are two issues I am running into:

1. Is there an argument to change the title of the plot? 

2. Is there an argument to change/add colors to the overlapping point-plot. It appears that there are only 4 colors by default(blue, green, purple and orange) so when a 5th phenotype is added to the plot it goes back to blue, making two different phenotypes have the same color for their respective points.

Any help would be greatly appreciated.

**Comment by hyacz** [comment]
Hello, 
Thank you for using MVP. Really happy to see you again.

Q1:  
Currently MVP has no parameters to modify the title of the plot. We will consider add this feature.

Q2:
You can use the **_col_** parameter to control what and how many colors to draw.

**Comment by hyacz** [comment]
This issue is closed because it is no longer active
