### ISSUE TITLE
Unusual FarmCPU results

### ISSUE THREAD

**Issue by strei102** [XiaoleiLiuBio/rMVP#30]
Hi,

I ran FarmCPU for multiple traits and I got quite unusual results. I attach a few manhattan plots to illustrate the issue. 

Cheers,

Stephan

![rectangular-manhattan trait4 farmcpu](https://user-images.githubusercontent.com/33267203/50356082-64cbad80-0516-11e9-9a39-171c6f5fb71a.jpg)
![rectangular-manhattan trait7 farmcpu](https://user-images.githubusercontent.com/33267203/50356099-757c2380-0516-11e9-8dfe-3bb526f729e4.jpg)
![rectangular-manhattan trait10 farmcpu](https://user-images.githubusercontent.com/33267203/50356100-757c2380-0516-11e9-9584-7682591537c8.jpg)
![rectangular-manhattan trait25 farmcpu](https://user-images.githubusercontent.com/33267203/50356101-757c2380-0516-11e9-9db0-0b949e25cdb0.jpg)
![rectangular-manhattan trait30 farmcpu](https://user-images.githubusercontent.com/33267203/50356102-757c2380-0516-11e9-9f92-434206ae55c8.jpg)
![rectangular-manhattan trait31 farmcpu](https://user-images.githubusercontent.com/33267203/50356103-757c2380-0516-11e9-850f-6c61b2fb9d54.jpg)

**Comment by hyacz** [comment]
This issue is closed because it is no longer active.
