### ISSUE TITLE
mvp.pc.txt and mvp.kin.txt

### ISSUE THREAD

**Issue by liqingbioinfo** [XiaoleiLiuBio/rMVP#31]
Hello Xiaolei

I have a problem while creating kinship files. I have loaded "mvp.geno.desc" as genotype in my R, but when I tries "MVP.Data.Kin(TRUE, mvp_prefix='mvp', out='mvp'", it does not work. 

```
>  MVP.Data.PC(TRUE, out='mvp', perc=1, pcs.keep=5)
Error in MVP.Data.PC(TRUE, out = "mvp", perc = 1, pcs.keep = 5) : 
   could not find function "MVP.Data.PC"
```

The same thing happened when I typed "MVP.Data.PC(TRUE, out='mvp', perc=1, pcs.keep=5)". How can I fix this problem? Otherwise, may I have your example the kinship file and Principal Components files? 

Best regards
Leah

**Comment by YinLiLin** [comment]
hi

Thank you for using of MVP!
There are two ways to calculate kinship and pc. First, it could be automatically outputted to your workplace when transforming your genetype by setting as following:
```r
MVP.Data(..., fileKin=TRUE, filePC=TRUE)
```
Second, you could use the corresponding functions to derive it if your genetype is already in required file format of MVP (.geno.desc, .geno.bin):
Loading your genotype to R:
```r
genotype <- attach.big.matrix("mvp.geno.desc")
```
For kinship:
```r
K <- MVP.K.VanRaden(genotype)
```
For PC
```r
PC <- MVP.PCA(genotype)
```
Please have a try with either above for your case, and any questions are welcome to discuss with us here.

Good luck,
Lilin

**Comment by hyacz** [comment]
Hi, Leah

`MVP.Data.Kin` and `MVP.Data.PC` are new functions that was recently added to MVP. If you are using an old version of MVP, you can use the following code to update to the latest version.

```
devtools::install_github("xiaoleiLiubio/rMVP")
```

Or use the `MVP.Data` function to do this, as LiLin Yin replied. I closed this issue, and if you have any new questions, you can open another issue.

Best,
Haohao
