### ISSUE TITLE
multiple trait analysis issues

### ISSUE THREAD

**Issue by Arthur1021** [XiaoleiLiuBio/rMVP#32]
Hello, Xiaolei,

I found single trait perform correctly, multiple traits analysis running with errors.(version 0.99.10)

> for(i in 2:ncol(phenotype)){imMVP <- MVP(phe=phenotype[, c(1, i)],geno=genotype,map=map,K=Kinship,nPC.GLM=5,nPC.MLM=3,nPC.FarmCPU=3,perc=1,priority="speed",vc.method="GEMMA",maxLoop=10,method.bin="FaST-LMM",permutation.threshold=TRUE,permutation.rep=100.threshold=0.05,method=c("GLM", "MLM", "FarmCPU"))}
Error: unexpected symbol in " 2:ncol(phenotype)){imMVP <- MVP(phe=phenotype[, c(1, i)],geno=genotype,map=map,K=Kinship,nPC.GLM=5,nPC.MLM=3,nPC.FarmCPU=3,perc=1,priority="speed",vc.method="GEMMA",maxLoop=10,method.bin="FaS"
Execution halted

**Comment by Arthur1021** [comment]
This is using latest version 0.99.10

**Comment by hyacz** [comment]
Hi,

Thank you for using MVP. There is a typo in the code you provide, `permutation.rep = 100` should be followed by a comma instead of a dot.

Best,
Haohao

**Comment by Arthur1021** [comment]
Thank you very much, it works.
