### ISSUE TITLE
infinite or missing values in 'x'

### ISSUE THREAD

**Issue by liubei8852** [XiaoleiLiuBio/rMVP#36]
I want to know if MVP need imputed data; can it used for nonimpued data

**Comment by hyacz** [comment]
MVP cannot run GWAS analysis with data containing NA, so when using MVP.Data for data format conversion, the NA is automatically imputed with the most common allele type. If you encounter an error, please provide detailed error information.

**Comment by liubei8852** [comment]
Thank you for answer my question, There is no other error.
