### ISSUE TITLE
best way to convert SNP genotype to numeric matrix

### ISSUE THREAD

**Issue by qgao2** [XiaoleiLiuBio/rMVP#9]
Hi Xiaolei, 
thanks a lot for writing this nice package. 
I would like to use MVP for my project, but I am not sure the best way to convert unphased SNP genotype (vcf format, around 60k SNPs) to numeric matrix (0,1,2). Do you which tool I should use to do the conversion.

**Comment by XiaoleiLiuBio** [comment]
I have written some codes for converting vcf to numeric, I will update the function in MVP soon.

**Comment by qgao2** [comment]
Nice!
Thank you, XiaoLei.

**Comment by hyacz** [comment]
The code for converting vcf to numeric has been added to MVP some time ago. You can use the following code to get a 012-encoded genotype matrix in `big.matrix` format. 

```
MVP.Data.VCF2MVP(fileVCF="my.vcf", out="my.mvp", threads=1)
geno <- attach.big.matrix("my.mvp.geno.desc")
```

1. `big.matrix` is mostly similar to `base::matrix` , if you want a real `base::matrix` you can use the following code:

```
geno <- geno[]
```

2. If you really need a 012-encoded genotype matrix text file, you can look at the write.big.matrix in the bigmemory package, which accepts a big.matrix

```
MVP.Data.VCF2MVP(fileVCF="my.vcf", out="my.mvp", threads=1)
geno <- attach.big.matrix("my.mvp.geno.desc")
write.big.matrix(geno, "my.numeric", sep=" ")
```

**Comment by hyacz** [comment]
This issue is closed because it is no longer active.
